# 구별 금연구역 개수 전처리
- 링크: http://data.seoul.go.kr/dataList/OA-20339/S/1/datasetView.do;jsessionid=A7C273F1FE87EF77EA255A781FAA4938.new_portal-svr-21

In [29]:
nodamZone_df = pd.read_csv('서울시 금연구역  정보(표준 데이터) (1).csv', encoding='cp949')
nodamZone_df.head(3)

,금연구역명,금연구역범위상세,시도명,시군구명,금연구역구분,금연구역지정근거명,금연구역면적,위반과태료,위반신고전화번호,소재지도로명주소,소재지지번주소,관리기관명,위도,경도,데이터기준일자,제공기관코드,작업일시
0,영등포초병설(공립),건물경계선으로부터 10m이내 보차도,서울특별시,영등포구,유치원 및 어린이집 전체 ...,서울특별시 영등포구 고시 제2014-18호,NaN,100000.0,02-2670-4895,서울특별시 영등포구 경인로 756,서울특별시 영등포구 문래동1가 35-2,서울특별시 영등포구청,37.512985,126.898260,2022-05-12,NaN,2022-07-17 11:37:01.0
1,도신초병설(공립),건물경계선으로부터 10m이내 보차도,서울특별시,영등포구,유치원 및 어린이집 전체 ...,서울특별시 영등포구 고시 제2014-18호,NaN,100000.0,02-2670-4895,서울특별시 영등포구 도림로 53길 32-9,서울특별시 영등포구 대림동 741-3,서울특별시 영등포구청,37.499268,126.900714,2022-05-12,NaN,2022-07-17 11:37:01.0
2,대방초병설(공립),건물경계선으로부터 10m이내 보차도,서울특별시,영등포구,유치원 및 어린이집 전체 ...,서울특별시 영등포구 고시 제2014-18호,NaN,100000.0,02-2670-4895,서울특별시 영등포구 여의대방로 35길 14,서울특별시 영등포구 신길동 1444,서울특별시 영등포구청,37.502900,126.919020,2022-05-12,NaN,2022-07-17 11:37:01.0

In [35]:
len(nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2019')]) # 2019

500

In [45]:
len(nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2020|2019')]) # 2020

852

In [46]:
len(nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2021|2020|2019')]) # 2021

7875

In [47]:
len(nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2022|2021|2020|2019')]) # 2022

10000

In [53]:
nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2022|2021|2020|2019')]['시군구명'].value_counts()

구로구     2069
노원구      964
강북구      885
서초구      780
영등포구     665
마포구      500
금천구      426
강남구      425
양천구      392
관악구      352
은평구      314
중구       311
종로구      309
중랑구      287
광진구      246
서대문구     210
강서구      195
송파구      158
동작구      134
성동구      134
강동구       97
용산구       86
성북구       61
Name: 시군구명, dtype: int64

In [54]:
nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2021|2020|2019')]['시군구명'].value_counts()

구로구     2069
노원구      964
서초구      780
마포구      500
금천구      426
강남구      425
양천구      392
관악구      352
은평구      314
중구       311
종로구      309
중랑구      287
서대문구     210
송파구      158
성동구      134
강동구       97
용산구       86
성북구       61
Name: 시군구명, dtype: int64

In [52]:
nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2020|2019')]['시군구명'].value_counts()

마포구    500
관악구    352
Name: 시군구명, dtype: int64

In [55]:
nodamZone_df[nodamZone_df['데이터기준일자'].str.contains('2019')]['시군구명'].value_counts()

마포구    500
Name: 시군구명, dtype: int64

In [89]:
nodamZone_gu_df = pd.DataFrame(nodamZone_df['시군구명'].value_counts()).reset_index()
nodamZone_gu_df.rename(columns={'index':'행정구역', '시군구명':'nodamZone'}, inplace=True)

In [90]:
nodamZone_gu_df

    행정구역  nodamZone
0    구로구       2069
1    노원구        964
2    강북구        885
3    서초구        780
4   영등포구        665
5    마포구        500
6    금천구        426
7    강남구        425
8    양천구        392
9    관악구        352
10   은평구        314
11    중구        311
12   종로구        309
13   중랑구        287
14   광진구        246
15  서대문구        210
16   강서구        195
17   송파구        158
18   동작구        134
19   성동구        134
20   강동구         97
21   용산구         86
22   성북구         61

In [91]:
sample_df = pd.read_csv('14~16년도 각자 데이터 채우기.csv', encoding='cp949')
sample_df.tail(4)

,Column1,집계년월,화재현황,행정구역,wood,usage,독거노인가구수,등록장애인수,인구밀도,소방장비(차량),건물평균연령,평균기온,평균강수량,평균습도,평균풍속,전기사용량(1000kwh),의용소방대원,소방대상물,주택수
2468,2468,2016.9.1,NaN,중랑구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2469,2469,2016.10.1,NaN,중랑구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2470,2470,2016.11.1,NaN,중랑구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2471,2471,2016.12.1,NaN,중랑구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
fire_total_nodam_Ver = pd.merge(sample_df, nodamZone_gu_df, how='outer', on=['행정구역'])
fire_total_nodam_Ver.head()

,Column1,집계년월,화재현황,행정구역,wood,usage,독거노인가구수,등록장애인수,인구밀도,소방장비(차량),건물평균연령,평균기온,평균강수량,평균습도,평균풍속,전기사용량(1000kwh),의용소방대원,소방대상물,주택수,nodamZone
0,0.0,2017.1.1,56.0,강남구,27.0,6732.0,10335.0,15200.0,13651.0,53.0,23.7293,-1.8,14.9,55.0,2.3,426547.0,200.0,13518.0,173282.0,425.0
1,1.0,2017.2.1,37.0,강남구,27.0,6732.0,10335.0,15200.0,13651.0,53.0,23.7293,-0.2,11.1,54.0,2.5,428437.0,200.0,13518.0,173282.0,425.0
2,2.0,2017.3.1,41.0,강남구,27.0,6732.0,10335.0,15200.0,13651.0,53.0,23.7293,6.3,7.9,48.0,2.4,372122.0,200.0,13518.0,173282.0,425.0
3,3.0,2017.4.1,46.0,강남구,27.0,6732.0,10335.0,15200.0,13651.0,53.0,23.7293,13.9,61.6,52.0,2.6,337248.0,200.0,13518.0,173282.0,425.0
4,4.0,2017.5.1,53.0,강남구,27.0,6732.0,10335.0,15200.0,13651.0,53.0,23.7293,19.5,16.1,52.0,2.4,317631.0,200.0,13518.0,173282.0,425.0

In [94]:
fire_total_nodam_Ver.to_csv('fire_total_nodamZone_Ver01.csv', encoding="utf-8-sig")