# 화재 피해규모 전처리

In [1]:
import pandas as pd

In [2]:
fire_damage = pd.read_csv('data/화재발생+현황(구별)(2017_2021).csv')
fire_damage

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건)
0,소계,2017,85590,15323890,283,37,246,148,794.0,5978
1,소계,2018,27008,21239984,360,53,307,360,911.0,6368
2,소계,2019,32221,92409010,398,37,361,318,921.0,5881
3,소계,2020,29895,17438606,273,37,236,300,386.0,5088
4,소계,2021,21723,18268346,317,37,280,597,383.0,4951
...,...,...,...,...,...,...,...,...,...,...
120,강북구,2017,652,339146,6,0,6,0,8.0,186
121,강북구,2018,211,216838,6,4,2,3,11.0,203
122,강북구,2019,693,217805,10,1,9,0,17.0,167
123,강북구,2020,398,208380,6,1,5,2,28.0,186
124,강북구,2021,488,410205,19,5,14,0,NaN,1

In [3]:
fire_damage['화재당_소실면적']=fire_damage['소실면적 (㎡)']/fire_damage['화재_발생 (건)']
fire_damage['화재당_피해액']=fire_damage['피해액 (천원)_합계']/fire_damage['화재_발생 (건)']
fire_damage['화재당_사망']=fire_damage['인명피해 (명)_사망']/fire_damage['화재_발생 (건)']
fire_damage['화재당_부상']=fire_damage['인명피해 (명)_부상']/fire_damage['화재_발생 (건)']
fire_damage['화재당_구조']=fire_damage['구조인원 (명)_합계']/fire_damage['화재_발생 (건)']
fire_damage['화재당_이재민']=fire_damage['이재민수 (명)_합계']/fire_damage['화재_발생 (건)']
fire_damage

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건),화재당_소실면적,화재당_피해액,화재당_사망,화재당_부상,화재당_구조,화재당_이재민
0,소계,2017,85590,15323890,283,37,246,148,794.0,5978,14.317497,2563.380729,0.006189,0.041151,0.132820,0.024757
1,소계,2018,27008,21239984,360,53,307,360,911.0,6368,4.241206,3335.424623,0.008323,0.048210,0.143059,0.056533
2,소계,2019,32221,92409010,398,37,361,318,921.0,5881,5.478830,15713.145724,0.006291,0.061384,0.156606,0.054072
3,소계,2020,29895,17438606,273,37,236,300,386.0,5088,5.875590,3427.398978,0.007272,0.046384,0.075865,0.058962
4,소계,2021,21723,18268346,317,37,280,597,383.0,4951,4.387598,3689.829529,0.007473,0.056554,0.077358,0.120582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,강북구,2017,652,339146,6,0,6,0,8.0,186,3.505376,1823.365591,0.000000,0.032258,0.043011,0.000000
121,강북구,2018,211,216838,6,4,2,3,11.0,203,1.039409,1068.167488,0.019704,0.009852,0.054187,0.014778
122,강북구,2019,693,217805,10,1,9,0,17.0,167,4.149701,1304.221557,0.005988,0.053892,0.101796,0.000000
123,강북구,2020,398,208380,6,1,5,2,28.0,186,2.139785,1120.322581,0.005376,0.026882,0.150538,0.010753
124,강북구,2021,488,410205,19,5,14,0,NaN,1,488.000000,410205.000000,5.000000,14.000000,NaN,0.000000

In [4]:
fire_damage['target_수치'] = 0.4* (fire_damage['화재당_사망']*0.8 + fire_damage['화재당_부상']*0.2) + 0.4*fire_damage['화재당_피해액'] + 0.2*fire_damage['화재당_이재민']
fire_damage.head()

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건),화재당_소실면적,화재당_피해액,화재당_사망,화재당_부상,화재당_구조,화재당_이재민,target_수치
0,소계,2017,85590,15323890,283,37,246,148,794.0,5978,14.317497,2563.380729,0.006189,0.041151,0.132820,0.024757,1025.362516
1,소계,2018,27008,21239984,360,53,307,360,911.0,6368,4.241206,3335.424623,0.008323,0.048210,0.143059,0.056533,1334.187676
2,소계,2019,32221,92409010,398,37,361,318,921.0,5881,5.478830,15713.145724,0.006291,0.061384,0.156606,0.054072,6285.276028
3,소계,2020,29895,17438606,273,37,236,300,386.0,5088,5.875590,3427.398978,0.007272,0.046384,0.075865,0.058962,1370.977421
4,소계,2021,21723,18268346,317,37,280,597,383.0,4951,4.387598,3689.829529,0.007473,0.056554,0.077358,0.120582,1475.962844

In [5]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [6]:
len(fire_damage)

125

In [7]:
q1=fire_damage['target_수치'].quantile(0.25)
q2=fire_damage['target_수치'].quantile(0.5)
q3=fire_damage['target_수치'].quantile(0.75)
iqr=q3-q1
iqr

748.6697045171517

### 분위수
- A

In [8]:
condition_A = fire_damage['target_수치']<q1
fire_damage[condition_A][fire_damage['소방서별(2)']=='강남구']

Empty DataFrame
Columns: [소방서별(2), 시점, 소실면적 (㎡), 피해액 (천원)_합계, 인명피해 (명)_합계, 인명피해 (명)_사망, 인명피해 (명)_부상, 이재민수 (명)_합계, 구조인원 (명)_합계, 화재_발생 (건), 화재당_소실면적, 화재당_피해액, 화재당_사망, 화재당_부상, 화재당_구조, 화재당_이재민, target_수치]
Index: []

In [9]:
condition_B = fire_damage['target_수치']>q3
fire_damage[condition_B][fire_damage['소방서별(2)']=='강남구']

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건),화재당_소실면적,화재당_피해액,화재당_사망,화재당_부상,화재당_구조,화재당_이재민,target_수치
51,강남구,2018,1631,1624983,23,0,23,1,36.0,436,3.740826,3727.025229,0.000000,0.052752,0.082569,0.002294,1490.814771
52,강남구,2019,1789,1677681,24,1,23,36,32.0,456,3.923246,3679.125000,0.002193,0.050439,0.070175,0.078947,1471.670526
53,강남구,2020,908,1451556,19,1,18,6,45.0,387,2.346253,3750.790698,0.002584,0.046512,0.116279,0.015504,1500.323928

In [10]:
condition_C = (fire_damage['target_수치']>=q1) & (fire_damage['target_수치']<=q3)
fire_damage[condition_C][fire_damage['소방서별(2)']=='강남구']

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건),화재당_소실면적,화재당_피해액,화재당_사망,화재당_부상,화재당_구조,화재당_이재민,target_수치
50,강남구,2017,2210,1565258,11,0,11,1,20.0,502,4.402390,3118.043825,0.000000,0.021912,0.039841,0.001992,1247.219681
54,강남구,2021,1909,1354949,17,2,15,35,36.0,391,4.882353,3465.342711,0.005115,0.038363,0.092072,0.089514,1386.159693

In [11]:
# condition=fire_damage['target_수치']<q1+1.5*iqr
# fire_damage[condition]

In [12]:
fire_damage

,소방서별(2),시점,소실면적 (㎡),피해액 (천원)_합계,인명피해 (명)_합계,인명피해 (명)_사망,인명피해 (명)_부상,이재민수 (명)_합계,구조인원 (명)_합계,화재_발생 (건),화재당_소실면적,화재당_피해액,화재당_사망,화재당_부상,화재당_구조,화재당_이재민,target_수치
0,소계,2017,85590,15323890,283,37,246,148,794.0,5978,14.317497,2563.380729,0.006189,0.041151,0.132820,0.024757,1025.362516
1,소계,2018,27008,21239984,360,53,307,360,911.0,6368,4.241206,3335.424623,0.008323,0.048210,0.143059,0.056533,1334.187676
2,소계,2019,32221,92409010,398,37,361,318,921.0,5881,5.478830,15713.145724,0.006291,0.061384,0.156606,0.054072,6285.276028
3,소계,2020,29895,17438606,273,37,236,300,386.0,5088,5.875590,3427.398978,0.007272,0.046384,0.075865,0.058962,1370.977421
4,소계,2021,21723,18268346,317,37,280,597,383.0,4951,4.387598,3689.829529,0.007473,0.056554,0.077358,0.120582,1475.962844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,강북구,2017,652,339146,6,0,6,0,8.0,186,3.505376,1823.365591,0.000000,0.032258,0.043011,0.000000,729.348817
121,강북구,2018,211,216838,6,4,2,3,11.0,203,1.039409,1068.167488,0.019704,0.009852,0.054187,0.014778,427.277044
122,강북구,2019,693,217805,10,1,9,0,17.0,167,4.149701,1304.221557,0.005988,0.053892,0.101796,0.000000,521.694850
123,강북구,2020,398,208380,6,1,5,2,28.0,186,2.139785,1120.322581,0.005376,0.026882,0.150538,0.010753,448.135054
124,강북구,2021,488,410205,19,5,14,0,NaN,1,488.000000,410205.000000,5.000000,14.000000,NaN,0.000000,164084.720000

# 년도별 피해규모 월별로 전처리

In [13]:
fire_damage02 = pd.read_csv('data/화재피해_201421(성동구제외).csv')
fire_damage02

    행정구역    시점  소실면적 (㎡)      피해액  사망  부상  이재민수  구조인원
0    종로구  2014      1697  1395325   0   1     2    17
1    종로구  2015      1462   566923   4   5     3     5
2    종로구  2016       499   394813   2  10     0     4
3    종로구  2017       832  1077665   1   3    20    16
4    종로구  2018       909   574300  14  22    44    60
..   ...   ...       ...      ...  ..  ..   ...   ...
179  강북구  2017       652   339146   0   6     0     8
180  강북구  2018       211   216838   4   2     3    11
181  강북구  2019       693   217805   1   9     0    17
182  강북구  2020       398   208380   1   5     2    28
183  강북구  2021       488   410205   5  14     0    10

[184 rows x 8 columns]

### 2022년도 데이터 채우기
- 구별 평균 (구별 증감추세가 일정하지 못함)

In [14]:
fire_damage_2022 = fire_damage02.groupby(by='행정구역').mean().reset_index()
fire_damage_2022['시점'] = 2022

# fire_damage_2022
fire_damage02 = pd.merge(fire_damage02, fire_damage_2022, how='outer').sort_values(['행정구역','시점']).reset_index(drop=True)
fire_damage02

    행정구역    시점  소실면적 (㎡)          피해액     사망    부상    이재민수    구조인원
0    강남구  2014  4106.000  1364100.000  1.000  17.0  115.00  23.000
1    강남구  2015  3899.000  2645324.000  0.000  19.0   13.00  43.000
2    강남구  2016  2567.000  2303012.000  5.000  25.0   19.00  15.000
3    강남구  2017  2210.000  1565258.000  0.000  11.0    1.00  20.000
4    강남구  2018  1631.000  1624983.000  0.000  23.0    1.00  36.000
..   ...   ...       ...          ...    ...   ...     ...     ...
202  중랑구  2018   893.000   201421.000  2.000   8.0    0.00  67.000
203  중랑구  2019   266.000   322650.000  1.000   9.0   24.00  34.000
204  중랑구  2020   374.000   229566.000  2.000  12.0    6.00  17.000
205  중랑구  2021   604.000   345257.000  1.000  12.0    3.00   4.000
206  중랑구  2022   820.125   318974.625  1.125  10.0    7.75  22.625

[207 rows x 8 columns]

In [15]:
# 성동구 제외: 성동소방서 건립이 2017년이기 때문에 2014년부터 2016년도 데이터가 없음
fire_df = pd.read_csv('data/last.csv')
sdGu_index = fire_df[fire_df['행정구역'] == '성동구'].index
fire_df = fire_df.drop(sdGu_index).reset_index(drop=True)
fire_df.head()

,집계년월,화재현황,행정구역,wood,usage,독거노인가구수,등록장애인수,인구밀도,소방장비(차량),건물평균연령,...,주택수,nodamZone,totalPopul,oldAgePopul,흡연자수,단독주택가스,교육의료가스,판매가스,기타가스,가스합계
0,2017.1.1,56,강남구,27,6732,11396,15617,14203,46,23.7293,...,173282,425.0,570500,39878,91850.0,15511,2339,24784,806,43440
1,2017.2.1,37,강남구,27,6732,11396,15617,14203,46,23.7293,...,173282,425.0,570500,39878,91850.0,17713,2666,30525,946,51850
2,2017.3.1,41,강남구,27,6732,11396,15617,14203,46,23.7293,...,173282,425.0,570500,39878,91850.0,13376,2286,23512,814,39988
3,2017.4.1,46,강남구,27,6732,11396,15617,14203,46,23.7293,...,173282,425.0,568425,40354,91516.0,9364,1922,13727,618,25631
4,2017.5.1,53,강남구,27,6732,11396,15617,14203,46,23.7293,...,173282,425.0,568425,40354,91516.0,4823,1147,7602,363,13935

In [16]:
fire_df['시점'] = fire_df['집계년월'].str[:4].astype('int64')
fire_df.head(2)

,집계년월,화재현황,행정구역,wood,usage,독거노인가구수,등록장애인수,인구밀도,소방장비(차량),건물평균연령,...,nodamZone,totalPopul,oldAgePopul,흡연자수,단독주택가스,교육의료가스,판매가스,기타가스,가스합계,시점
0,2017.1.1,56,강남구,27,6732,11396,15617,14203,46,23.7293,...,425.0,570500,39878,91850.0,15511,2339,24784,806,43440,2017
1,2017.2.1,37,강남구,27,6732,11396,15617,14203,46,23.7293,...,425.0,570500,39878,91850.0,17713,2666,30525,946,51850,2017

### 화재건수 비율계산
- 수집한 데이터가 월별이 아닌 년도별이기떄문에 화재건수의 월별 비율을 구해 월별 피해규모 데이터 생성

In [17]:
# 비율함수
def x_prop(group):
    group['fire_prop'] = group.화재현황 / group.화재현황.sum()
    return group

In [18]:
fire_df = fire_df.groupby(['시점', '행정구역']).apply(x_prop)
fire_df.head(3)

,집계년월,화재현황,행정구역,wood,usage,독거노인가구수,등록장애인수,인구밀도,소방장비(차량),건물평균연령,...,totalPopul,oldAgePopul,흡연자수,단독주택가스,교육의료가스,판매가스,기타가스,가스합계,시점,fire_prop
0,2017.1.1,56,강남구,27,6732,11396,15617,14203,46,23.7293,...,570500,39878,91850.0,15511,2339,24784,806,43440,2017,0.111554
1,2017.2.1,37,강남구,27,6732,11396,15617,14203,46,23.7293,...,570500,39878,91850.0,17713,2666,30525,946,51850,2017,0.073705
2,2017.3.1,41,강남구,27,6732,11396,15617,14203,46,23.7293,...,570500,39878,91850.0,13376,2286,23512,814,39988,2017,0.081673

In [19]:
fd_merge_df = pd.merge(fire_damage02, fire_df, how='outer', left_on=['시점', '행정구역'], right_on=['시점', '행정구역'])
fd_merge_df.rename(columns={'소실면적 (㎡)': '소실면적'}, inplace=True)

fd_merge_df['소실면적'] = fd_merge_df.fire_prop * fd_merge_df.소실면적
fd_merge_df['피해액'] = fd_merge_df.fire_prop * fd_merge_df.피해액
fd_merge_df['사망'] = fd_merge_df.fire_prop * fd_merge_df.사망
fd_merge_df['부상'] = fd_merge_df.fire_prop * fd_merge_df.부상
fd_merge_df['이재민수'] = fd_merge_df.fire_prop * fd_merge_df.이재민수
fd_merge_df['구조인원'] = fd_merge_df.fire_prop * fd_merge_df.구조인원

fd_merge_df

,행정구역,시점,소실면적,피해액,사망,부상,이재민수,구조인원,집계년월,화재현황,...,nodamZone,totalPopul,oldAgePopul,흡연자수,단독주택가스,교육의료가스,판매가스,기타가스,가스합계,fire_prop
0,강남구,2014,433.732394,144095.070423,0.105634,1.795775,12.147887,2.429577,2014.1.1,45,...,425.0,570701,32995,97019.0,17046,2365,27510,817,47738,0.105634
1,강남구,2014,308.431925,102467.605634,0.075117,1.276995,8.638498,1.727700,2014.2.1,32,...,425.0,570701,32995,97019.0,16931,2594,32472,901,52898,0.075117
2,강남구,2014,346.985915,115276.056338,0.084507,1.436620,9.718310,1.943662,2014.3.1,36,...,425.0,570701,32995,97019.0,13730,2151,24862,787,41530,0.084507
3,강남구,2014,433.732394,144095.070423,0.105634,1.795775,12.147887,2.429577,2014.4.1,45,...,425.0,574226,33528,97618.0,9249,1696,13016,566,24527,0.105634
4,강남구,2014,424.093897,140892.957746,0.103286,1.755869,11.877934,2.375587,2014.5.1,44,...,425.0,574226,33528,97618.0,5435,1125,8062,356,14978,0.103286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2364,중랑구,2022,133.650000,51981.050000,0.183333,1.629630,1.262963,3.687037,2022.3.1,22,...,287.0,393600,46410,NaN,15118,468,2204,1874,19664,0.162963
2365,중랑구,2022,103.275000,40167.175000,0.141667,1.259259,0.975926,2.849074,2022.4.1,17,...,287.0,393147,47097,NaN,9334,321,1427,1789,12871,0.125926
2366,중랑구,2022,157.950000,61432.150000,0.216667,1.925926,1.492593,4.357407,2022.5.1,26,...,287.0,393147,47097,NaN,0,0,0,0,0,0.192593
2367,중랑구,2022,133.650000,51981.050000,0.183333,1.629630,1.262963,3.687037,2022.6.1,22,...,287.0,393147,47097,NaN,0,0,0,0,0,0.162963
2368,중랑구,2022,109.350000,42529.950000,0.150000,1.333333,1.033333,3.016667,2022.7.1,18,...,287.0,393147,47097,NaN,0,0,0,0,0,0.133333

### 월별 피해규모 데이터

In [20]:
monthOfFireDamage_df = fd_merge_df.iloc[:, :10].drop(columns=['시점'])
monthOfFireDamage_df.to_csv('monthOfFireDamage_df.csv', encoding='utf-8-sig')

In [21]:
sdf

NameError: name 'sdf' is not defined

# 사용할 데이터

In [ ]:
fire_df.isnull().sum()

In [ ]:
# fire_simple_df = fire_df.drop(columns=['독거노인가구수', '등록장애인수', '소방장비(차량)', '평균기온', '평균강수량', '평균습도', '평균풍속', '소방대상물', 'nodamZone', '흡연자수', 'wood', 'usage', 'fire_prop', '시점', '교육의료가스', '판매가스', '기타가스', 'oldAgePopul'])
# fire_simple_df.head()
fire_simple_df = fire_df.drop(columns=['nodamZone', '흡연자수', '평균기온', '평균강수량'])
fire_simple_df.head()

## 1. 의용소방대원 결측치 처리
- 구별 평균

In [ ]:
# 각 구별 의용소방대원 수 평균으로 결측값 처리
for i in fire_simple_df['행정구역'].unique():
      fire_simple_df[fire_simple_df['행정구역']==i] = fire_simple_df[fire_simple_df['행정구역']==i].fillna(value=fire_simple_df[fire_simple_df['행정구역']==i]['의용소방대원'].mean())

In [ ]:
fire_total_df = pd.merge(fire_simple_df, monthOfFireDamage_df)
fire_total_df.head(3)

In [ ]:
# fire_total_df.to_csv('fire_total_df(월별피해규모포함).csv', encoding='utf-8-sig')

In [ ]:
# fire_total_df_feature = fire_total_df.drop(columns=['집계년월', '행정구역'])
# fire_total_df_target = fire_total_df['행정구역']

fire_simple_feature = fire_simple_df.drop(columns=['집계년월', '행정구역', '의용소방대원'])
fire_simple_target = fire_simple_df['행정구역']

## K-mean

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
def elbow(X):
  sse = []
  for i in range(1, 11):
    km = KMeans(n_clusters=i, init='k-means++', random_state=0)
    km.fit(X)
    sse.append(km.inertia_)

  plt.plot(range(1, 11), sse, marker='o')
  plt.xlabel('num_clurster')
  plt.ylabel('SSE')
  plt.show()

In [ ]:
### 여러개의 클러스터링 갯수를 List로 입력 받아 각각의 실루엣 계수를 면적으로 시각화한 함수 작성
def visualize_silhouette(cluster_lists, X_features):     
    from sklearn.datasets import make_blobs
    from sklearn.cluster import KMeans
    from sklearn.metrics import silhouette_samples, silhouette_score

    import matplotlib.pyplot as plt
    import matplotlib.cm as cm
    import math
   
    # 입력값으로 클러스터링 갯수들을 리스트로 받아서, 각 갯수별로 클러스터링을 적용하고 실루엣 개수를 구함
    n_cols = len(cluster_lists)
   
    # plt.subplots()으로 리스트에 기재된 클러스터링 수만큼의 sub figures를 가지는 axs 생성 
    fig, axs = plt.subplots(figsize=(4*n_cols, 4), nrows=1, ncols=n_cols)
   
    # 리스트에 기재된 클러스터링 갯수들을 차례로 iteration 수행하면서 실루엣 개수 시각화
    for ind, n_cluster in enumerate(cluster_lists):
       
        # KMeans 클러스터링 수행하고, 실루엣 스코어와 개별 데이터의 실루엣 값 계산. 
        clusterer = KMeans(n_clusters = n_cluster, max_iter=500, random_state=0)
        cluster_labels = clusterer.fit_predict(X_features)
       
        sil_avg = silhouette_score(X_features, cluster_labels)
        sil_values = silhouette_samples(X_features, cluster_labels)
       
        y_lower = 10
        axs[ind].set_title('Number of Cluster : '+ str(n_cluster)+'\n' \
                          'Silhouette Score :' + str(round(sil_avg,3)) )
        axs[ind].set_xlabel("The silhouette coefficient values")
        axs[ind].set_ylabel("Cluster label")
        axs[ind].set_xlim([-0.1, 1])
        axs[ind].set_ylim([0, len(X_features) + (n_cluster + 1) * 10])
        axs[ind].set_yticks([])  # Clear the yaxis labels / ticks
        axs[ind].set_xticks([0, 0.2, 0.4, 0.6, 0.8, 1])
       
        # 클러스터링 갯수별로 fill_betweenx( )형태의 막대 그래프 표현. 
        for i in range(n_cluster):
            ith_cluster_sil_values = sil_values[cluster_labels==i]
            ith_cluster_sil_values.sort()
           
            size_cluster_i = ith_cluster_sil_values.shape[0]
            y_upper = y_lower + size_cluster_i
           
            color = cm.nipy_spectral(float(i) / n_cluster)
            axs[ind].fill_betweenx(np.arange(y_lower, y_upper), 0, ith_cluster_sil_values, \
                                facecolor=color, edgecolor=color, alpha=0.7)
            axs[ind].text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))
            y_lower = y_upper + 10

        axs[ind].axvline(x=sil_avg, color="red", linestyle="--")

In [ ]:
elbow(fire_simple_feature)

In [ ]:
# cluster 개수를 3개, 4개, 5개, 6개 일때의 클러스터별 실루엣 계수 평균값을 시각화 
visualize_silhouette([4, 5, 6, 7], fire_simple_feature)

In [ ]:
k = 6
# kmeans = KMeans(n_clusters=k)
kmeans = KMeans(n_clusters=k, init='k-means++', max_iter=300,random_state=0).fit(fire_simple_feature)
print(kmeans.labels_)

In [ ]:
fire_simple_df['cluster'] = kmeans.labels_
fire_simple_result = fire_simple_df.groupby(['행정구역','cluster'])['화재현황'].count()
cluster_result = pd.DataFrame(fire_simple_result).sort_values(by='cluster', ascending=False).reset_index()
cluster_result[cluster_result['화재현황'] > 50].reset_index(drop=True) # 70: 과반수개념)

In [ ]:
# level = ['A', 'B', 'C', 'D', 'E', 'F']
# # 강남구: 고위험, (송파구, 강서구): 위험, (양천구, 구로구, 은평구, 관악구, 강동구, 성북구): 다소위험, (영등포구, 서초구): 주의, (용산구, 종로구, 중구): 양호, (서대문구, 성동구, 동작구, 동대문구, 도봉구, 광진구, 강북구, 중랑구): 모범
# B = ['송파구', '강서구']
# C = ['양천구', '구로구', '은평구', '관악구', '강동구', '성북구']
# D = ['영등포구', '서초구']
# E = ['용산구', '종로구', '중구']
# F = ['서대문구', '성동구', '동작구', '동대문구', '도봉구', '광진구', '강북구', '중랑구']

level = ['A', 'B', 'C', 'D', 'E']
A = ['강남구']
B = ['동대문구', '서대문구']
C = ['영등포구', '서초구', '광진구', '구로구']
D = ['송파구', '양천구', '강서구', '관악구', '은평구', '종로구', '마포구', '성북구']
E = ['용산구', '동작구', '강동구', '중랑구', '도봉구', '노원구', '강북구']

In [ ]:
fire_simple_df['target'] = np.nan

for i in fire_simple_df['행정구역'].unique():
  if i == '강남구':
    fire_simple_df[fire_simple_df['행정구역'] == i] = fire_simple_df[fire_simple_df['행정구역'] == i].fillna('A')
  elif i in B:
    fire_simple_df[fire_simple_df['행정구역'] == i] = fire_simple_df[fire_simple_df['행정구역'] == i].fillna('B')
  elif i in C:
    fire_simple_df[fire_simple_df['행정구역'] == i] = fire_simple_df[fire_simple_df['행정구역'] == i].fillna('C')
  elif i in D:
    fire_simple_df[fire_simple_df['행정구역'] == i] = fire_simple_df[fire_simple_df['행정구역'] == i].fillna('D')
  else:
    fire_simple_df[fire_simple_df['행정구역'] == i] = fire_simple_df[fire_simple_df['행정구역'] == i].fillna('E')

fire_simple_df

In [ ]:
fire_total_df = pd.concat([fire_total_df, fire_simple_df.target], axis=1)
fire_total_df.head(3)

In [ ]:
# sns.pairplot(fire_total_df.drop(columns = ['집계년월', '행정구역', 'target', '의용소방대원']))
# plt.show()
fire_total_df.drop(columns = ['집계년월', '행정구역', 'target']).corr()['의용소방대원'].sort_values(ascending = False)

### Scaling

In [ ]:
# fire_total_df_rbS = fire_total_df.drop(columns = ['집계년월', '행정구역', 'target'])
# fire_total_df_rbS

In [ ]:
# from sklearn.preprocessing import RobustScaler

# rb_scaler = RobustScaler()
# fire_total_df_rbS.iloc[:,:] = rb_scaler.fit_transform(fire_total_df_rbS)
# fire_total_df_rbS

In [ ]:
# fire_total_df_rbS

In [ ]:
fire_total_feature = fire_total_df.drop(columns = ['집계년월', '행정구역', 'target', '의용소방대원'])
fire_total_target = fire_total_df.의용소방대원
fire_total_feature.columns

In [ ]:
condition_A = fire_total_df[fire_total_df.target == 'A'].index
condition_F = fire_total_df[(fire_total_df.target == 'F')].index #| (fire_total_df.target == 'E') | (fire_total_df.target == 'D')].index

In [ ]:
X_train = fire_total_feature.iloc[condition_F]
y_train = fire_total_target.iloc[condition_F]


X_test = fire_total_feature.iloc[condition_A]
y_test = fire_total_target.iloc[condition_A]

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=20)

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVR

# index로 데이터를 구분해서 학습
models = []
scores = []
for i, (train_idx, val_idx) in enumerate(kf.split(X_train)):
    
    train_feature = X_train.iloc[train_idx]
    val_data_feature = X_train.iloc[val_idx]
    
    train_label = y_train.iloc[train_idx]
    val_data_label = y_train.iloc[val_idx]
    
    # 모델 객체
    model = LinearRegression()   
    model.fit(train_feature, train_label)
    models.append(model)
    
    val_score = model.score(val_data_feature, val_data_label)
    scores.append(val_score)
    print(i, np.round(val_score, 4))

print("*"*10)
print(np.round(np.mean(scores), 4))

In [ ]:
pred = model.predict(X_test)

In [ ]:
pd.DataFrame([pred, y_test])

## 데이터 년도별 병합
- 기존 월별 데이터셋 학습시 데이터가 월별의 영향을 많이 받고 있는것으로 판단

In [ ]:
fire_total_df['집계년'] = fire_total_df['집계년월'].str[:4].astype('int64')
fire_total_df.columns

In [ ]:
test_merge = fire_total_df.drop(columns=['집계년월']).groupby(['집계년', '행정구역', 'target']).sum().reset_index()
test_merge
# test_merge.to_csv('data/test_merge.csv', encoding='utf-8-sig')

In [ ]:
# fireMen = pd.read_csv('data/소방+공무원(정원).csv')
# fireMen = fireMen.rename(columns={'소방서별(2)':'행정구역', '시점':'집계년'}).drop(columns='소방서별(1)')

In [ ]:
test_merge.의용소방대원.sort_values(ascending=False)

In [ ]:
test_merge.의용소방대원 = test_merge.의용소방대원/12
test_merge.iloc[:,14:]

In [ ]:
# test_merge

In [ ]:
# test_merge = pd.merge(test_merge, fireMen, how='outer', on=['집계년', '행정구역'])
# test_merge

In [ ]:
# # 각 구별 의용소방대원 수 평균으로 결측값 처리
# for i in test_merge['행정구역'].unique():
#       test_merge[test_merge['행정구역']==i] = test_merge[test_merge['행정구역']==i].fillna(value=test_merge[test_merge['행정구역']==i]['의용소방대원'].mean())

# test_merge

In [ ]:
# # test_merge_sc = test_merge.iloc[:,3:].drop(columns='의용소방대원')
# # test_merge_sc
# test_merge.iloc[:,3:-1]

In [ ]:
# from sklearn.preprocessing import RobustScaler

# rb_scaler = RobustScaler()
# test_merge.iloc[:,3:-1] = rb_scaler.fit_transform(test_merge.iloc[:,3:-1])
# test_merge

In [ ]:
# total_df = pd.read_csv('data/fire_total_dataset.csv').drop(columns='Unnamed: 0')
# total_df

In [ ]:
# # 각 구별 의용소방대원 수 평균으로 결측값 처리
# for i in total_df['행정구역'].unique():
#       total_df[total_df['행정구역']==i] = total_df[total_df['행정구역']==i].fillna(value=total_df[total_df['행정구역']==i]['의용소방대원'].mean())

# total_df

In [ ]:
# sns.pairplot(fire_total_df.drop(columns = ['집계년월', '행정구역', 'target', '의용소방대원']))
# plt.show()
test_merge.drop(columns = [ '집계년', '행정구역', 'target', 'fire_prop', '시점']).corr()['의용소방대원'].sort_values(ascending = False)

In [ ]:
plt.figure(figsize=(15,15))
plt.rc('font', family='NanumGothic')
sns.heatmap(data = test_merge.drop(columns = ['집계년', '행정구역', 'target', '시점']).corr(), annot=True, 
fmt = '.2f', linewidths=.5, cmap='Blues')

In [ ]:
test_merge.columns

In [ ]:
# test_merge = test_merge.sample(frac=1, random_state=42)
test_merge.to_csv('data/check_dataset.csv', encoding='utf-8-sig')

In [ ]:
condition_A = test_merge[test_merge.target == 'A'].index
condition_F = test_merge[(test_merge.target == 'E') | (test_merge.target == 'D') | (test_merge.target == 'C')].index

In [ ]:
test_merge_feature = test_merge.drop(columns = ['집계년', '행정구역', 'target', '시점', '의용소방대원', 'fire_prop', 'wood', '소실면적', '단독주택가스', '교육의료가스', '판매가스', '기타가스', '등록장애인수', '소실면적', '피해액', '사망', '부상', '이재민수', '구조인원'])
test_merge_target = test_merge.의용소방대원
test_merge_feature.columns

In [ ]:
X_train = test_merge_feature.iloc[condition_F]
y_train = test_merge_target.iloc[condition_F]


X_test = test_merge_feature.iloc[condition_A]
y_test = test_merge_target.iloc[condition_A]

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=20)

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor

# index로 데이터를 구분해서 학습
models = []
scores = []
for i, (train_idx, val_idx) in enumerate(kf.split(X_train)):
    
    train_feature = X_train.iloc[train_idx]
    val_data_feature = X_train.iloc[val_idx]
    
    train_label = y_train.iloc[train_idx]
    val_data_label = y_train.iloc[val_idx]
    
    # 모델 객체
    # model = AdaBoostRegressor(random_state=144, n_estimators=500, learning_rate=0.1) 
    model = GradientBoostingRegressor(random_state=42, n_estimators=100, max_depth=4, learning_rate=0.05)
    # model = Lasso()
    model.fit(train_feature, train_label)
    models.append(model)
    
    val_score = model.score(val_data_feature, val_data_label)
    scores.append(val_score)
    print(i, np.round(val_score, 4))

print("*"*10)
print(np.round(np.mean(scores), 4))

In [ ]:
pred = model.predict(X_train)

In [ ]:
pd.DataFrame([pred, y_train])

In [ ]:
pred = model.predict(X_test)

In [ ]:
pd.DataFrame([pred, y_test])

## 재분류
- 기존 클러스터링 + 사분위수 이용

In [ ]:
fire_total_df

In [ ]:
# from sklearn.linear_model import Ridge
# from sklearn.metrics import mean_squared_error

In [ ]:
# ridge = Ridge().fit(X_train, y_train)
# y_pred = ridge.predict(X_test)

# print(f'훈련 데이터 점수 : {ridge.score(X_train, y_train) : .4f}')
# print(f'검증 데이터 점수 : {ridge.score(X_test, y_test) : .4f}')
# print(f'MSE : {mean_squared_error(y_test, y_pred) : .4f}')

In [ ]:
# from sklearn.linear_model import Lasso

# lasso = Lasso().fit(X_train, y_train)
# y_pred = lasso.predict(X_test)

# print(f'훈련 데이터 점수 : {ridge.score(X_train, y_train) : .4f}')
# print(f'검증 데이터 점수 : {ridge.score(X_test, y_test) : .4f}')
# print(f'MSE : {mean_squared_error(y_test, y_pred) : .4f}')

In [ ]:
# monthOfFireDamage_df.drop(columns=['시점', '행정구역', '집계년월'], inplace=True)
# monthOfFireDamage_df

In [ ]:
# monthOfFireDamage_df_rbS = monthOfFireDamage_df.copy()
# monthOfFireDamage_df_rbS

In [ ]:
# from sklearn.preprocessing import RobustScaler

# rb_scaler = RobustScaler()
# monthOfFireDamage_df_rbS.iloc[:,:] = rb_scaler.fit_transform(monthOfFireDamage_df_rbS)
# monthOfFireDamage_df_rbS

In [ ]:
# monthOfFireDamage_df_rbS['target_수치'] = 0.4* (monthOfFireDamage_df_rbS['사망']*0.6 + monthOfFireDamage_df_rbS['부상']*0.4) + 0.3*monthOfFireDamage_df_rbS['피해액'] + 0.2*monthOfFireDamage_df_rbS['소실면적'] + 0.1*monthOfFireDamage_df_rbS['이재민수']
# monthOfFireDamage_df_rbS.head()

monthOfFireDamage_df['target_수치'] = 0.4* (monthOfFireDamage_df_rbS['사망']*0.6 + monthOfFireDamage_df_rbS['부상']*0.4) + 0.3*monthOfFireDamage_df_rbS['피해액'] + 0.2*monthOfFireDamage_df_rbS['소실면적'] + 0.1*monthOfFireDamage_df_rbS['이재민수']
monthOfFireDamage_df.head()

In [ ]:
q1_1=monthOfFireDamage_df['target_수치'].quantile(0.125)
q1_2=monthOfFireDamage_df['target_수치'].quantile(0.25)
q2=monthOfFireDamage_df['target_수치'].quantile(0.50)
q3_1=monthOfFireDamage_df['target_수치'].quantile(0.75)
q3_2=monthOfFireDamage_df['target_수치'].quantile(0.875)


iqr=q3_2-q1_2
iqr

In [ ]:
# condition_A = monthOfFireDamage_df['target_수치']<q1_1
# monthOfFireDamage_df_rbS[condition_A][monthOfFireDamage_df_rbS['행정구역']=='강남구']

In [ ]:
# condition_B = (monthOfFireDamage_df['target_수치']>=q1_1) & (fire_damage['target_수치']<q1_2)
# monthOfFireDamage_df_rbS[condition_B][monthOfFireDamage_df_rbS['행정구역']=='강남구']

In [ ]:
# condition_C = (monthOfFireDamage_df['target_수치']>=q1_2) & (fire_damage['target_수치']<=q3_1)
# monthOfFireDamage_df_rbS[condition_C][monthOfFireDamage_df_rbS['행정구역']=='강남구']

In [ ]:
# condition_D = (monthOfFireDamage_df['target_수치']>q3_1) & (fire_damage['target_수치']<=q3_2)
# monthOfFireDamage_df_rbS[condition_D][monthOfFireDamage_df_rbS['행정구역']=='강남구']

In [ ]:
# condition_E = monthOfFireDamage_df['target_수치']>q3_2
# monthOfFireDamage_df_rbS[condition_E][monthOfFireDamage_df_rbS['행정구역']=='강남구']